.TH ADR2LINE200 1 2/23/19 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
adr2line200 \- Honeywell 200/2000 debug info
.SH SYNOPSIS
.B adr2line200
[
.I options
]
.IR adr ...
.SH DESCRIPTION
.B Adr2line200 
displays debug information from H200/H2000 object files
compiled with \fB-g\fR. If no file is specified, "a.out" is used.

For each \fIadr\fR, information that is available in the
symbol table is displayed.
At a minimum, the file and line number are printed (if available).
Note that stripped object files have no information,
and only files compiled with \fB-g\fR contain line numbers.

.SH OPTIONS
.TP 
.BI \-a
Print the address. This is particularly useful when
multiple address are given. Addresses are printed in octal.
.TP 
.BI \-e\  file
Use \fIfile\fR to gather information.
.TP 
.BI \-f
Print the function name.

.SH "SEE ALSO"
ld200 (1), 
nm200 (1), 
objdump200 (1),
a.out.200 (5).
.SH DIAGNOSTICS
.SH BUGS
