.TH AR200 I 3/15/72 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
ar200 \- archive and library maintainer
.SH SYNOPSIS
.B ar200
.I key afile name\fR...
.SH DESCRIPTION
.B Ar200
maintains groups of files
combined into a single archive file.
Its main use
is to create and update library files as used by the loader.
It can be used, though, for any similar purpose.

.I Key
is one character from the set
.BR drtux ,
optionally concatenated with
.BR v .
.I Afile
is the archive file.
The
.I names
are constituent files in the archive file.
The meanings of the
.I key
characters are:
.TP
.B d
means delete the named files from the archive file.
.TP
.B r
means replace the named files in the archive file.
If the archive file does not exist,
.B r
creates it.
If the named files are not in the archive file, they are appended.
.TP
.B t
prints a table of contents of the archive file.
If no names are given, all files in the archive are tabled.
If names are given, only those files are tabled.
.TP
.B u
is similar to
.B r
except that only those
files that have been modified are replaced.
If no names are given, all files in the archive that
have been modified are replaced by the modified version.
.TP
.B x
extracts the named files.
If no names are given, all files in the archive are
extracted.
In neither case does
.B x
alter the archive file.
.TP
.B v
means verbose.
Under the verbose option,
.I ar
gives a file-by-file
description of the making of a
new archive file from the old archive and the constituent files.
The following abbreviations
are used:
.IP
.B "   c"
copy
.B "   a"
append
.B "   d"
delete
.B "   r"
replace
.B "   x"
extract
.SH FILES
/tmp/vtm?	temporary
.SH "SEE ALSO"
ld200 (1), archive200 (5)
.SH BUGS
Option
.B tv
should be implemented as a table with more information.

There should be a way to specify the placement
of a new file in an archive.
Currently, it is placed at the end.

Since
.B ar200
has not been rewritten to
deal properly with the new file system
modes,
extracted files have mode 666.

For the same reason,
only the first 8 characters of file names are significant.

If the same file is mentioned twice in an argument list,
it may be put in the archive twice.
