.TH BRFDUMP 1 5/19/22 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
brfdump \- Honeywell 200/2000 BRF dump
.SH SYNOPSIS
.B brfdump
[ \fIoptions\fR ]
.I file
[ \.\.\. ]
.SH DESCRIPTION
.B Brfdump
prints the contents of an H200/H2000 BRF file.

.SH OPTIONS
.TP
.BI \-c
Input is a card deck file (default is mag tape image).
.TP
.BI \-d
Prefix each BRF control with synthesized DIST address.
.TP
.BI \-o
Prefix each BRF control with record number and record offset.
.TP
.BI \-r\  len
Use \fIlen\fR as record length in mag tape image.
.TP
.BI \-s
Use the alternate (special) HW card encoding for punch card format.
This corresponds to PCB control character 26 on the H200/2000 reader/punch control.

.PP
The BRF file should not contain bootstrap records.

.SH "SEE ALSO"
out2boot (1),
out2brf (1),
.SH DIAGNOSTICS
.SH BUGS
