.TH LD200 1 8/16/73 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
ld200  \-  link editor
.SH SYNOPSIS
.B ld200
[
.B \-sulxrdni
]
.IR name ...
.SH DESCRIPTION
.B Ld200
combines several
object programs into one; resolves external
references; and searches libraries.
In the simplest case the names of several object
programs are given, and
.B ld
combines them, producing
an object module which can be either executed or
become the input for a further
.B ld
run.
(In the latter case, the
.B \-r
option must be given
to preserve the relocation bits.)
The output of
.B ld
is left on
.B a.out.
This file is made executable
only if no errors occurred during the load.

The argument routines are concatenated in the order
specified.  The entry point of the output is the
beginning of the first routine.

If any argument is a library, it is searched exactly once
at the point it is encountered in the argument list.
Only those routines defining an unresolved external
reference are loaded.
If a routine from a library
references another routine in the library,
the referenced routine must appear after the
referencing routine in the library.
Thus the order of programs within libraries
is important.

.B Ld
understands several flag arguments which are written
preceded by a `\-'.
Except for \fB\-l\fR,
they should appear before the file names.

.SH OPTIONS
.TP
\fB\-s\fR
`squash' the output, that is, remove the symbol table
and relocation bits to save space (but impair the
usefulness of the debugger).
This information can also be removed by
.BR strip .
.TP
\fB\-g\fR
Preserve debug info symbols (symbols that begin with '~').
.TP
\fB\-u\fR\ \fIname\fR
Take \fIname\fR as a symbol and enter
it as undefined in the symbol table.  This is useful
for loading wholly from a library, since initially the symbol
table is empty and an unresolved reference is needed
to force the loading of the first routine.
.TP
\fB\-l\fR
This option is an abbreviation for a library name.
\fB\-l\fR
alone stands for `/lib/liba.a', which
is the standard system library for assembly language
programs.
\fB\-l\fIx\fR
stands for `/lib/lib\fIx\fR.a' where \fIx\fR is any string.
A library is searched when its name is encountered,
so the placement of a \fB\-l\fR
is significant. This option does not allow a space between
\fB\-l\fR and \fIx\fR.
.TP
\fB\-L\fIpath\fR
Add \fIpath\fR to the list of directories searched for libraries.
No space is allowed between \fB\-L\fR and \fIpath\fR.
.TP
\fB\-x\fR
do not preserve local
(non-.globl) symbols in the output symbol table; only enter
external symbols.
This option saves some space in the output file.
.TP
\fB\-X\fR
Save local symbols
except for those whose names begin with `L'.
This option is used by
.B cc
to discard internally generated labels while
retaining symbols local to routines.
.TP
\fB\-r\fR
generate relocation bits in the output file
so that it can be the subject of another
.B ld
run.
This flag also prevents final definitions from being
given to common symbols,
and suppresses the `undefined symbol' diagnostics.
.TP
\fB\-d\fR
force definition of common storage
even if the
.B \-r
flag is present.
.TP
\fB\-n\fR
Arrange that
when the output file is executed,
the text portion will be read-only and shared
among all users executing the file.
This involves moving the data areas up the the first
possible 4K word boundary following the
end of the text.
.TP
\fB\-i\fR
When the output file is executed, the program
text and data areas will live in separate address spaces.
The only difference between this option
and
.B \-n
is that here the data starts at location 0.
.TP
\fB\-a\fR\ \fIadr\fR
Use \fIadr\fR as the "entry" address, which is also the load address.
Default for H200 is 1340 (decimal), which is adequate for MOD1 applications.
.TP
\fB\-t\fR\ \fIlen\fR
Use \fIlen\fR as the stack size, or simply additional space added to \fB.bss\fR.
Default is zero (no additional space). since this number is not communicated
to the program when it runs, there is no automatic method to setup a stack.
.TP
\fB\-o\fR\ \fIname\fR
Use \fIname\fR as the output file name, instead of \fBa.out\fR.
.PP
.SH FILES
/lib/lib?.a   libraries

a.out   output file
.SH "SEE ALSO"
as200 (1), ar200 (1)
.SH BUGS
