.TH OBJDUMP200 1 1/15/73 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
objdump200 \- Honeywell 200/2000 object file dumper
.SH SYNOPSIS
.B objdump200
[ \fIoptions\fR ]
.IR file ...
.SH DESCRIPTION
.B Objdump200
displays information about H200/H2000 object files.

.SH OPTIONS
.TP
.BI \-a\  admode
Provide address mode hint when disassembling object files
without reloc info. Values 2, 3, or 4.
.TP
.BI \-d
Disassemble the \fB.text\fR section. Sections with zero-length
are not listed.
.TP
.BI \-h
Display header information.
.TP
.BI \-s
Dump section data. Default is both \fB.text\fR and \fB.data\fR.
.TP
.BI \-H
Use Honeywell-style dump format for \fB-s\fR.
.TP
.BI \-j\  sect
Use \fIsect\fR as the object file section for \fB-s\fR.
Only \fB.text\fR or \fB.data\fR is recognized.
.TP
.BI \-r
Display relocation/symbol information with \fB-d\fR.
.TP
.BI \-w\  width
Provide a hint to the terminal line length, for \fB-s\fR.
.TP
.BI \-S
Generate, to stdout, the as200 source code for set word- and item-mark
preamble for the specified object file.
This includes an extra word-mark after the last character.
Currently only works for a single object file,
assuming \.text and \.data are contiguous.
Default address mode is 3.
Use \fB-a\fR to change.
Looks for a global symbol for location 0, and uses that
in the SW/SI instructions as the base address.
If no global symbol is found, "base" is used.
Typically, this code is assembled into a \.o and
linked in front the object file to produce a bootstrap image.
.TP
.BI \-N\  addr
With \fB-S\fR, generate a standalone SW/SI block using \fIaddr\fR 
as the base/load address for the object code.
Also appends a branch to \fIaddr\fR (with punctuation setup).
This is for cases where the punctuation setup is not be
part of the loaded program, for example for Card Loader
where space is a premium.

.SH "SEE ALSO"
ld200 (1),
nm200 (1),
a.out.200 (5).
.SH DIAGNOSTICS
.SH BUGS
