.TH OUT2BRF 1 5/14/22 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
out2brf \- Honeywell 200/2000 object file to Binary Run Format
.SH SYNOPSIS
.B out2brf
[ \fIoptions\fR ]
.I file
.SH DESCRIPTION
.B Out2brf
converts an H200/H2000 object file into a mag tape or card deck BRF image,
suitable for use with the simulators and HW Loader/Monitor programs.

.SH OPTIONS
.TP
.BI \-b
Output in bootstrap format (banner 042 records).
Uses a restricted subset of BRF.
.TP
.BI \-c
Output in punch card format, instead of mag tape.
.TP
.BI \-e\  entry
Use \fIentry\fR as the start location, instead of the first load address.
.TP
.BI \-s
Use the alternate (special) HW card encoding for punch card format.
This corresponds to PCB control character 26 on the H200/2000 reader/punch control.
.TP
.BI \-m\  number
Create a minimum of \fInumber\fR records.
A warning is printed if \fInumber\fR is exceeded.
.TP
.BI \-o\  file
Send output to \fIfile\fR instead of stdout.
Note that the output is binary, so it cannot be displayed on a terminal.
.TP
.BI \-P\  program
Set the program name used in the segment header record.
Default is derived from the file name.
.TP
.BI \-S\  segment
Set the program segment used in the segment header record.
Default is "01".
.TP
.BI \-R\  revision
Set the program revision number used in the segment header record.
Default is "000".
.TP
.BI \-V\  visibility
Set the program visibility key used in the segment header record.
Default is 0400000000000 (a.k.a. "A").

.SH "SEE ALSO"
out2boot (1),
brfdump (1),
pcddump (1),
ld200 (1),
a.out.200 (5).
.SH DIAGNOSTICS
.SH BUGS
