.TH SIZE200 1 9/2/72 "binutils-H200" "Honeywell 200/2000 Tools"
.SH NAME
size200 \- size of an object file
.SH SYNOPSIS
.B size200
[
.IR object ...
]
.SH DESCRIPTION
.B Size200
prints the (decimal) number of bytes
required by the
text, data, and bss
portions, and their sum in octal and decimal,
of each object-file argument.
If no file is specified,
.B a.out
is used.
.SH BUGS
