#!/bin/bash

cat <<EOF
<HTML><CENTER>
Reproducing Punch Simulator<BR>
Build: $(date)<BR>
<BR>
<IMG SRC="ibm514-sm.png">
<BR>
Developed by Douglas Miller<BR>
http://sims.durgadas.com/<BR>
<BR>
</CENTER></HTML>
EOF
